<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net4.7.2</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Quarry</RootNamespace>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <None Update="manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BlishHUD" Version="1.0.0" ExcludeAssets="runtime" />
    <PackageReference Include="Flurl.Http" Version="2.4.2" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.42" />
    <PackageReference Include="TmfLib" Version="2.2.5" />
    <PackageReference Include="System.ComponentModel.Composition" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Quarry.WikiData\Quarry.WikiData.csproj" />
  </ItemGroup>
</Project>
